default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shelf_share_development

test:
  <<: *default
  database: shelf_share_test

production:
  <<: *default
  database: shelf_share_production
  username: shelf_share
  password: <%= ENV['SHELF_SHARE_DATABASE_PASSWORD'] %>
